### ISSUE TITLE
Running Warp Drive in Slicer from Lead DBS

### ISSUE THREAD

**Issue by christiane1708** [netstim/SlicerNetstim#17]
Hi,

I am using Lead DBS 2.6 and followed the instructions here https://netstim.gitbook.io/leaddbs/appendix/warpdrive to implement warp drive. When calling the Refine Atlas Fit from the Lead DBS GUI the warp drive menu is opened, but I get the follwing error that the data cannot be loaded:
Adding data failes. Error occured while loading the selected files. See attachment.

Any ideas how to solve this issue?

Thanks!!!

![ErrorMEssageWarpDrive](https://github.com/netstim/SlicerNetstim/assets/94974325/0eef08d7-3626-4cb2-9b87-a3ed360b33e1)

**Comment by simonoxen** [comment]
Hi, I'd highly recommend to use lead dbs in develop version to run warpdrive, since it incorporates a better implementation to launch it. We plan to make a release in the following months.

For debugging this case, I think better if you could send a complete log? Open Slicer->help->report a bug->copy the log from warpdrive session.

**Comment by christiane1708** [comment]
Hi, Thanks for the fast reply. Here is the complete logfile of the error message:

DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Operating system .........: Windows /  Professional / (Build 14393, Code Page 1252) - 64-bit
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Memory ...................: 32659 MB physical, 45459 MB virtual
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - CPU ......................: GenuineIntel , 8 cores, 8 logical processors
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Developer mode ...........: disabled
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Application path .........: C:/Users/Weinrich_Christiane/AppData/Local/NA-MIC/Slicer 5.2.2/bin
[DEBUG][Qt] 12.07.2023 13:10:37 [] (unknown:0) - Additional module paths ..: NA-MIC/Extensions-31382/MarkupsToModel/lib/Slicer-5.2/qt-loadable-modules, NA-MIC/Extensions-31382/SlicerRT/lib/Slicer-5.2/cli-modules, NA-MIC/Extensions-31382/SlicerRT/lib/Slicer-5.2/qt-loadable-modules, NA-MIC/Extensions-31382/SlicerRT/lib/Slicer-5.2/qt-scripted-modules, C:\toolboxes\leaddbs-classic\ext_libs\SlicerNetstim\ImportAtlas, C:\toolboxes\leaddbs-classic\ext_libs\SlicerNetstim\WarpDrive
[DEBUG][Python] 12.07.2023 13:10:41 [Python] (C:\Users\Weinrich_Christiane\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 12.07.2023 13:10:42 [Python] (C:\Users\Weinrich_Christiane\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 12.07.2023 13:10:42 [Python] (C:\Users\Weinrich_Christiane\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:38) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 12.07.2023 13:10:42 [] (unknown:0) - Switch to module:  "Welcome"
[DEBUG][Qt] 12.07.2023 13:10:43 [] (unknown:0) - Local filepath received via command-line:  "C:\\toolboxes\\leaddbs-classic\\"
[DEBUG][Qt] 12.07.2023 13:10:43 [] (unknown:0) - Local filepath received via command-line:  "G:\\Patienten\\done\\STN\\078_hm_STN"
[WARNING][Qt] 12.07.2023 13:10:43 [] (unknown:0) - void __cdecl qSlicerIOManager::showLoadNodesResultDialog(bool,class vtkMRMLMessageCollection *) Errors occurred while loading nodes: "- Error: Loading C:/toolboxes/leaddbs-classic/ -  load failed.\n- Error: Loading G:/Patienten/done/STN/078_hm_STN -  load failed.\n"

I tried to use the develop version of lead dbs. However, I cannot open the lead dbs gui with the develop version due to another error. 

Thanks

**Comment by simonoxen** [comment]
Thanks, hard to tell though.

Since we will be switching to that in the following months, I'd be more in favor of fixing the error you get in lead-dbs develop version.

**Comment by christiane1708** [comment]
Hi Simon, thanks for the reply. Here is the error message I get when trying to open the lead dbs gui in develop version.

Warning: Not all atlas data is present. Please click on 'Install' -> 'Redownload data files' to download the required files 
Warning: Not all atlas data is present. Please click on 'Install' -> 'Redownload data files' to download the required files 
Warning: Not all atlas data is present. Please click on 'Install' -> 'Redownload data files' to download the required files 
Warning: Not all atlas data is present. Please click on 'Install' -> 'Redownload data files' to download the required files 
Warning: Not all atlas data is present. Please click on 'Install' -> 'Redownload data files' to download the required files 
Error using lead>lead_OpeningFcn (line 87)
Error defining property 'Hyperlink' of class 'lead_dbs'. Class named 'matlab.ui.control.Hyperlink' is undefined or does not support property
validation.

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in lead (line 42)
    gui_mainfcn(gui_State, varargin{:});

Best

christiane

**Comment by simonoxen** [comment]
I see. Any chance you can update your matlab to something >=2021b?

If not, you can open the lead_dbs.mlapp and in the _Design View_ delete the `lead-dbs.org` hyperlink component.
