### ISSUE TITLE
WarpDrive usability improvements

### ISSUE THREAD

**Issue by lassoan** [netstim/SlicerNetstim#3]
- [x] describe limitations in the readme.md file (only grid transform is accepted as input, line is not visible in Slicer Preview Release, SlicerANTs is not available for Slicer Stable Release)
- [x] create 15-30 second demo video of WarpDrive
- [x] explicitly set fiducial display properties (defaults are different for every user)
- [x] add single-click undo (maybe redo as well? probably not needed)
- [x] use waitcursor during lengthy operations and pause rendering using slicer.app.pauseRender()/slicer.app.resumeRender()
- [x] update the transform automatically after clicking delete
- [x] line is not visible in preview release, probably it would be better to use markups
- [x] add atlas button does not work
- [x] remove segments section
- [x] add a volume selector or make the input selector work for volumes and transforms

**Comment by simonoxen** [comment]
Thanks! I think all of these have been addressed by now
